"""
Django settings for DjangoCrud project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import environ
import os

BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environment variables
env = environ.Env()

# Read .env file
env.read_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# ALLOWED_HOSTS = [
#    "192.168.0.214",
#    "http://localhost:3000",
#     "http://localhost:5173",
#     "http://127.0.0.1:5173",
#     "127.0.0.1",
#     "shawanda-abiding-rayne.ngrok-free.dev",
#     "localhost",
#     "https://shawanda-abiding-rayne.ngrok-free.dev",
#     "*.ngrok-free.dev",
    
# ]

ALLOWED_HOSTS = ["*"]

CSRF_TRUSTED_ORIGINS = [
    "https://shawanda-abiding-rayne.ngrok-free.dev",
    "http://localhost:3000",
    "http://localhost:8000",
    "http://192.168.0.214:8000",
    "https://*.ngrok-free.dev",
    "http://localhost:5173",
    
]

# CORS Configuration - Order and specificity matter for proper preflight handling
# Use CORS_ALLOW_ALL_ORIGINS for development to fix ngrok issues
# CORS_ALLOW_ALL_ORIGINS = True  # Set to True for development with ngrok

# If you want to restrict origins in production, comment above and uncomment below:
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://192.168.0.214:8000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "https://shawanda-abiding-rayne.ngrok-free.dev",
    "https://*.ngrok-free.dev",
    "http://localhost:8000",
    
]

CORS_ALLOW_CREDENTIALS = True

# Specify explicit methods instead of wildcard for better browser compatibility
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

# Specify explicit headers instead of wildcard when using credentials
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "ngrok-skip-browser-warning",
]


# Important: Allow preflight requests to be cached to reduce OPTIONS calls
CORS_PREFLIGHT_MAX_AGE = 86400  # 24 hours




INSTALLED_APPS = [
    "corsheaders", # Allowing cross-origin requests for API access 
    "django.contrib.admin", 
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'rest_framework_simplejwt',  # JWT authentication support
    "rest_framework",# Django REST Framework for building APIs
    # 'rest_framework.authtoken',
    "usermangement", # Custom app handling user management features
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # Middleware to handle CORS headers - MUST be at the top
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware", # Standard Django middleware for common tasks
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "DjangoCrud.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


 

WSGI_APPLICATION = "DjangoCrud.wsgi.application" # WSGI application entry point


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_USER_MODEL = 'usermangement.User'  # Use the custom User model from the 'usermangement' app instead of default Django User

AUTH_PASSWORD_VALIDATORS = [
    { "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator", },
    { "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator", },
    { "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator", },
    { "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator", },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
# Media files configuration
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        "rest_framework_simplejwt.authentication.JWTAuthentication" # Use JWT authentication for API requests
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # Changed to AllowAny to allow signup without authentication
    ]
}

# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # Emails will be printed to console instead of sending
# EMAIL_HOST_USER = 'kuldeep.t@amenitytech.ai'  # Default "from" email address for sending emails

# Use SMTP backend for live emails
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# SMTP server details
EMAIL_HOST = 'smtp.gmail.com'          # Gmail SMTP server
EMAIL_PORT = 587                       # TLS port
EMAIL_USE_TLS = True                   # Use TLS for security

# Load email credentials from environment variables
EMAIL_HOST_USER = env("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")

SIMPLE_JWT = {
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}
 
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=int(os.getenv("ACCESS_TOKEN_LIFETIME"))),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=int(os.getenv("REFRESH_TOKEN_LIFETIME"))),
}

